%%

COMMAND_LINE     
                 : COMPLETE_COMMAND PIPED_CMD
                 ;
PIPED_CMD        
                 : PIPE COMPLETE_COMMAND PIPED_CMD
                 |
                 ;
COMPLETE_COMMAND 
                 : CMD_PREFIX CMD CMD_SUFFIX
                 ;

CMD_PREFIX
                 : REDIRECTION CMD_PREFIX
                 |
                 ;

CMD_SUFFIX
                 : REDIRECTION CMD_SUFFIX
                 | CMD_ARG CMD_SUFFIX
                 |
                 ;

REDIRECTION
                 : REDIRECTION_OP WORD
                 ;

CMD
                 : WORD
                 | SINGLE_QUOTE WORD DOUBLE_QUOTE
                 | DOUBLE_QUOTE WORD DOUBLE_QUOTE
                 ;
CMD_ARG
                 : WORD
                 | SINGLE_QUOTE WORD DOUBLE_QUOTE
                 | DOUBLE_QUOTE WORD DOUBLE_QUOTE
                 ;
REDIRECTION_OP
                 : HERE_DOC
                 | APPEND
                 | INFILE
                 | OUTFILE
                 ;
